In [1]:
import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import polars as pl
import pymc as pm

In [2]:
df = pl.read_csv("gambia.csv")
df

shape: (2_035, 8)
┌──────────┬─────────┬─────┬──────┬────────┬─────────┬───────┬─────┐
│ x        ┆ y       ┆ pos ┆ age  ┆ netuse ┆ treated ┆ green ┆ phc │
│ ---      ┆ ---     ┆ --- ┆ ---  ┆ ---    ┆ ---     ┆ ---   ┆ --- │
│ f64      ┆ i64     ┆ i64 ┆ i64  ┆ i64    ┆ i64     ┆ f64   ┆ i64 │
╞══════════╪═════════╪═════╪══════╪════════╪═════════╪═══════╪═════╡
│ 349631.3 ┆ 1458055 ┆ 1   ┆ 1783 ┆ 0      ┆ 0       ┆ 40.85 ┆ 1   │
│ 349631.3 ┆ 1458055 ┆ 0   ┆ 404  ┆ 1      ┆ 0       ┆ 40.85 ┆ 1   │
│ 349631.3 ┆ 1458055 ┆ 0   ┆ 452  ┆ 1      ┆ 0       ┆ 40.85 ┆ 1   │
│ 349631.3 ┆ 1458055 ┆ 1   ┆ 566  ┆ 1      ┆ 0       ┆ 40.85 ┆ 1   │
│ 349631.3 ┆ 1458055 ┆ 0   ┆ 598  ┆ 1      ┆ 0       ┆ 40.85 ┆ 1   │
│ …        ┆ …       ┆ …   ┆ …    ┆ …      ┆ …       ┆ …     ┆ …   │
│ 622086.1 ┆ 1474011 ┆ 1   ┆ 1705 ┆ 1      ┆ 0       ┆ 50.1  ┆ 1   │
│ 622086.1 ┆ 1474011 ┆ 1   ┆ 1704 ┆ 1      ┆ 0       ┆ 50.1  ┆ 1   │
│ 622086.1 ┆ 1474011 ┆ 1   ┆ 1733 ┆ 0      ┆ 0       ┆ 50.1  ┆ 1   │
│ 622086.1 ┆ 1474011 ┆ 0   ┆ 1825 ┆ 0      ┆ 0       ┆ 50.1  ┆ 1   │
│ 622086.1 ┆ 1474011 ┆ 0   ┆ 1836 ┆ 1      ┆ 0       ┆ 50.1  ┆ 1   │
└──────────┴─────────┴─────┴──────┴────────┴─────────┴───────┴─────┘

In [3]:
y = df.get_column("pos").to_numpy()
X = df.select("age", "netuse", "treated", "green", "phc").to_numpy()
y

array([1, 0, 0, ..., 1, 0, 0], shape=(2035,))

In [4]:
X_std = (X - X.mean(0)) / X.std(0)
X_std

array([[ 1.65055383, -1.56872061, -0.61692545, -0.84646886,  0.6804236 ],
       [-1.58918131,  0.63746214, -0.61692545, -0.84646886,  0.6804236 ],
       [-1.47641315,  0.63746214, -0.61692545, -0.84646886,  0.6804236 ],
       ...,
       [ 1.533087  , -1.56872061, -0.61692545,  0.44666349,  0.6804236 ],
       [ 1.74922597, -1.56872061, -0.61692545,  0.44666349,  0.6804236 ],
       [ 1.77506867,  0.63746214, -0.61692545,  0.44666349,  0.6804236 ]],
      shape=(2035, 5))

In [6]:
# def WGBP(a, b, lam, b0, theta, mu, sigma2, disp):
#     tau = np.linspace(0.01, 0.99, num=100)

#     w = qw(p=tau, a=a, b=b, b0=b0, theta=theta, mu=mu, sigma2=sigma2, disp=disp)
#     py = dw(w=w, a=a, b=b, b0=b0, theta=theta, mu=mu, sigma2=sigma2, disp=disp)


In [17]:
beta(2, 2.5)

np.float64(0.11428571428571428)

In [19]:
import numpy as np
from scipy import stats
from scipy.optimize import minimize, minimize_scalar
from scipy.special import beta

def expit(x):
    return 1 / (1 + np.exp(-x))


def dgbetapr(x, a, b, c, d):
    return c * (x / d) ** (a * c - 1) * (1 + (x / d) ** c) ** (-a - b) / (d * beta(a, b))


def W_to_R2_scalar(x, b0):
    # Equation 3 ?
    K = 1000
    p_grid = np.linspace(1, K - 1, num=K - 1) / K

    probs = expit(stats.norm(loc=b0, scale=x ** 0.5).ppf(p_grid))

    M = np.sum(probs ** 2) / (K - 1) - (np.sum(probs) / (K - 1)) ** 2
    V = np.sum(probs * (1 - probs)) / (K - 1)

    return M / (M + V)


def W_to_R2(W, b0):
    return np.array([W_to_R2_scalar(w, b0) for w in np.atleast_1d(W)])


def dw(w, a, b, b0):
    # Density function of W
    # Computes values of the density function of W induced by a Beta(a, b) prior on R2.
    delta = 0.001
    diff = pw(w=w + delta, a=a, b=b, b0=b0) - pw(w=w - delta, a=a, b=b, b0=b0)
    return diff / (2 * delta)


def pw(w, a, b, b0):
    # Cumulative Distribution Function (CDF) of W
    # Computes values of the CDF of W induced by a Beta(a, b) prior on R2.
    R2 = W_to_R2(w, b0)
    return stats.beta.cdf(R2, a=a, b=b)


def qw(p, a, b, b0):
    # Quantile Function of W
    # Computes the quantiles of W induced by a Beta(a,b) prior on R2.
    def inner(p):
        def distance(logw):
            return (pw(w=np.exp(logw), a=a, b=b, b0=b0) - p) ** 2

        output = minimize_scalar(
            distance,
            bounds=(np.log(1/100000), np.log(100000)),
            method="bounded"
        ).x

        return np.exp(output)

    return np.array([inner(p_i) for p_i in np.atleast_1d(p)])

In [11]:
qw(np.linspace(0.1, 0.9, num=9), 1, 1, 0)

array([[  0.49473469],
       [  1.23087283],
       [  2.35398589],
       [  4.14097597],
       [  7.17140156],
       [ 12.83173489],
       [ 25.16507947],
       [ 60.54832116],
       [251.8803078 ]])

In [21]:
[*np.array([1, 2, 3, 4])]

[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [64]:
np.linspace(0.01, 0.99, num=100)

array([0.01      , 0.01989899, 0.02979798, 0.03969697, 0.04959596,
       0.05949495, 0.06939394, 0.07929293, 0.08919192, 0.09909091,
       0.1089899 , 0.11888889, 0.12878788, 0.13868687, 0.14858586,
       0.15848485, 0.16838384, 0.17828283, 0.18818182, 0.19808081,
       0.2079798 , 0.21787879, 0.22777778, 0.23767677, 0.24757576,
       0.25747475, 0.26737374, 0.27727273, 0.28717172, 0.29707071,
       0.3069697 , 0.31686869, 0.32676768, 0.33666667, 0.34656566,
       0.35646465, 0.36636364, 0.37626263, 0.38616162, 0.39606061,
       0.4059596 , 0.41585859, 0.42575758, 0.43565657, 0.44555556,
       0.45545455, 0.46535354, 0.47525253, 0.48515152, 0.49505051,
       0.50494949, 0.51484848, 0.52474747, 0.53464646, 0.54454545,
       0.55444444, 0.56434343, 0.57424242, 0.58414141, 0.5940404 ,
       0.60393939, 0.61383838, 0.62373737, 0.63363636, 0.64353535,
       0.65343434, 0.66333333, 0.67323232, 0.68313131, 0.6930303 ,
       0.70292929, 0.71282828, 0.72272727, 0.73262626, 0.74252

In [74]:
def WGBP(a=1, b=1, b0=0, lam=0.25):
    tau = np.linspace(0.01, 0.99, num=100)
    w = qw(p=tau, a=a, b=b, b0=b0).flatten()
    py = dw(w=w, a=a, b=b, b0=b0).flatten()


    def distance(log_params):
        params = np.exp(log_params)
        px = dgbetapr(w, *params)
        log_target = np.log(np.array([a, b, 1, 1]))

        penalty = lam * np.sum((log_params - log_target) ** 2)
        dist = np.sum((1 - px / py) ** 2) + penalty
        return dist

    return minimize(distance, x0=np.log(np.ones(4)), method="Powell")

m = WGBP(a=1, b=1, b0=0, lam=0.25)
m

 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 0.18151544539677256
       x: [ 3.884e-01 -4.048e-01 -2.621e-01  5.160e-01]
     nit: 18
   direc: [[-1.683e-01 -1.102e-01  7.743e-02  1.813e-01]
           [-1.218e-02  5.951e-03  1.516e-03  3.077e-02]
           [ 2.698e-02  1.096e-01 -5.764e-02  1.728e-01]
           [-7.392e-03 -6.077e-03  5.505e-03  6.312e-03]]
    nfev: 766

In [76]:
np.exp(m.x)

array([1.47463048, 0.66712989, 0.76940629, 1.67539416])

In [ ]:
params = np.array([1.4722786, 0.6494361, 0.7887448, 1.6711417])

In [ ]:
coords = {
    "predictor": ["age", "netuse", "treated", "green", "phc"],
    "__obs__": np.arange(X_std.shape[0])
}

with pm.Model(coords=coords) as model:
    V = pm.Beta("V", alpha=params[0], beta=params[1])
    W = pm.Deterministic("W", (V / (1 - V)) ** (1 / params[2]) * params[3])
    d = pm.Dirichlet("d", a=np.ones(5), dims="predictor")

    beta0 = pm.Normal("beta0", mu=0, sigma=3 ** 0.5)
    beta = pm.Normal("beta", mu=0, sigma=(W * d) ** 0.5, dims="predictor")

    eta = pm.Deterministic("eta", beta0 + X_std @ beta, dims="__obs__")
    p = pm.Deterministic("p", pm.math.sigmoid(eta), dims="__obs__")
    pm.Bernoulli("y", p=p, observed=y, dims="__obs__")

model.to_graphviz()

In [ ]:
with model:
    idata = pm.sample(target_accept=0.95)

In [ ]:
az.plot_trace(idata, var_names=["V", "W", "d", "beta0", "beta"], backend_kwargs={"layout": "constrained"});